server:
  port: 8080

spring:
  application:
    name: onboarding

  data:
    data:
      mongodb:
        host: localhost
        port: 27017
        database: onboarding
        username: admin
        password: password