server:
  port: 8080

spring:
  application:
    name: onboarding
  data:
    mongodb:
      uri: mongodb://localhost:27017/onboarding

default:
  user:
    role: ADMIN
    status: SUBMITTED
  organization:
    status: SUBMITTED
  need-code: true
